[package]
name = "ferum"
version = "0.1.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "testnet" }
FerumSTD = { git = "https://github.com/ferum-dex/ferum-std.git", rev = "testnet" }

[addresses]
ferum="0xb9a9606eeeb416eef9cd8650c34c0d16b7a650f207830a22d77e743c53d9902a"
